update hc_tipo_reg set cant_Campos=98 where id_tipo_Reg=21;
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'MOTIVO GENERAL:',null,59,'MOTIVO GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'PATOLOGICOS:',null,60,'PATOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'TRAUMATICOS:',null,61,'TRAUMATICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'QUIRURGICOS:',null,62,'QUIRURGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'ENF. TRASMISION SEXUAL:',null,63,'ENF. TRASMISION SEXUAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'INMUNOLOGICOS:',null,64,'INMUNOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'ALERGICOS:',null,65,'ALERGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'FARMACOLOGICOS:',null,66,'FARMACOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'TOXICOS:',null,67,'TOXICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'NUTRICIONALES:',null,68,'NUTRICIONALES:');
--REVISION POR SISTEMA
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'GENERAL:',null,69,'GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'CABEZA:',null,70,'CABEZA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'OJOS:',null,71,'OJOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'NARIZ:',null,72,'NARIZ:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'OIDOS:',null,73,'OIDOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'OROFARINGE:',null,74,'OROFARINGE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'CUELLO:',null,75,'CUELLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'RESPIRATORIO:',null,76,'RESPIRATORIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'ENDOCRINO:',null,77,'ENDOCRINO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'MUSCULO ESQUELETICO:',null,78,'MUSCULO ESQUELETICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'HEMATOPOYETICO:',null,79,'HEMATOPOYETICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'LINFORRETICULAR:',null,80,'LINFORRETICULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'PSIQUIATRICOS:',null,81,'PSIQUIATRICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'PIEL Y FANERAS:',null,82,'PIEL Y FANERAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'ARTICULAR:',null,83,'ARTICULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'CARDIOVASCULAR:',null,84,'CARDIOVASCULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'GASTRO - INTESTINAL:',null,85,'GASTRO - INTESTINAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'GINECOLOGICO:',null,86,'GINECOLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'UROLOGICO:',null,87,'UROLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'OTROS:',null,88,'OTROS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'APARIENCIA GENERAL:',null,89,'APARIENCIA GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'ATENCION:',null,90,'ATENCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'MEMORIA:',null,91,'MEMORIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'ALTERACION DEL SUEÑO:',null,92,'ALTERACION DEL SUEÑO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'APETITO:',null,93,'APETITO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'PENSAMIENTO:',null,94,'PENSAMIENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'SOMATIZACIONES:',null,95,'SOMATIZACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'INTROSPECCION Y PROSPECCION:',null,96,'INTROSPECCION Y PROSPECCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,21,'AFECTO:',null,97,'AFECTO:');
