insert into hc_tipo_reg
values(83,'HISTORIA CLINICA PREVENCION DE ENFERMEDADES CRONICAS','s_historia_prevencion_enfermedades_cronicas.xhtml',true,226,0);

---Antes de ejecutar los registros actualizar la secuencia hc_campos_reg_id_campo_seq al último valor de la tabla hc_campos_reg

insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'MOTIVO DE CONSULTA',null,0,'MOTIVO DE CONSULTA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ENFERMEDAD ACTUAL:',null,1,'ENFERMEDAD ACTUAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CEFALEA:',null,2,'CEFALEA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'LIPOTOMIA:',null,3,'LIPOTOMIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'VERTIGO:',null,4,'VERTIGO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TINITUS: ',null,5,'TINITUS: ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'STOMAS VISUALES:',null,6,'STOMAS VISUALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SUDURACION',null,7,'SUDURACION');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PALPITACIONES:',null,8,'PALPITACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'EPITAXIS:',null,9,'EPITAXIS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PRECORDIALGIA:',null,10,'PRECORDIALGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ORTOPNEA:',null,11,'ORTOPNEA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'DISNEA:',null,12,'DISNEA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'POLIDIPA:',null,13,'POLIDIPA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'POLIFAGIA:',null,14,'POLIFAGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'POLIURIA:',null,15,'POLIURIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'HEMATURIA:',null,16,'HEMATURIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'DISURIA:',null,17,'DISURIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'EDEMA:',null,18,'EDEMA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CLAUDICACION:',null,19,'CLAUDICACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'LEON DE PIES:  ',null,20,'LEON DE PIES:  ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'DOLOR NEURITICO:',null,21,'DOLOR NEURITICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'NCOPE:',null,22,'NCOPE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FOSFES:',null,23,'FOSFES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FOTOFOBIA',null,24,'FOTOFOBIA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TOS:',null,25,'TOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'HEMOPTIS:',null,26,'HEMOPTIS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'POLAQUIURIA:',null,27,'POLAQUIURIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'NICTURIA:',null,28,'NICTURIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'IMPOTENCIA SEXUAL:',null,29,'IMPOTENCIA SEXUAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PERDIDA DE PESO:',null,30,'PERDIDA DE PESO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ALTERAACON DE LA MARCHA:',null,31,'ALTERAACON DE LA MARCHA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ALTERACION DEL EQUILIBRIO:',null,32,'ALTERACION DEL EQUILIBRIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SE AGITA AL CAMINAR(Distancia):',null,33,'SE AGITA AL CAMINAR(Distancia):');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'OBSERVACIONES',null,34,'OBSERVACIONES');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'HIPERTEN:      ',null,35,'HIPERTEN:      ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ENFERMEDAD CEREBROVASCULAR:',null,36,'ENFERMEDAD CEREBROVASCULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ICC-ICT:',null,37,'ICC-ICT:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ANGINA:',null,38,'ANGINA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'IAM:',null,39,'IAM:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ICR:',null,40,'ICR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ENFERMEDAD ENDOCRINA:',null,41,'ENFERMEDAD ENDOCRINA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ENFERMEDAD RENAL:',null,42,'ENFERMEDAD RENAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'OBEDAD:',null,43,'OBEDAD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ENFERMEDAD VASCULAR:',null,44,'ENFERMEDAD VASCULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'DEABETES:',null,45,'DEABETES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'DISLIPIDEMIA:',null,46,'DISLIPIDEMIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'RETIPATIA:',null,47,'RETIPATIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'EPOC:',null,48,'EPOC:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ASMA:',null,49,'ASMA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TBC:',null,50,'TBC:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TRAUMAS:',null,51,'TRAUMAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'HTA-DM EMBARAZO:',null,52,'HTA-DM EMBARAZO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CA PROSTATA:',null,53,'CA PROSTATA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CA GASTRICO:',null,54,'CA GASTRICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CA SE:',null,55,'CA SE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CA CERVIX:',null,56,'CA CERVIX:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ALERGICOS ',null,57,'ALERGICOS ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'QUIRURGICOS:',null,58,'QUIRURGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TOXICOS',null,59,'TOXICOS');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'OCUPACIONALES:',null,60,'OCUPACIONALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'COMPLICAION ORGA BLANCO:',null,61,'COMPLICAION ORGA BLANCO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'OTROS',null,62,'OTROS');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'OBSERVACIONES:',null,63,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'MENARQUIAS/ESPERMARCA:',null,64,'MENARQUIAS/ESPERMARCA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FECHA ULTIMA MENSTRUACION:',null,65,'FECHA ULTIMA MENSTRUACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'MEPAUA:',null,66,'MEPAUA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'GESTAS:',null,67,'GESTAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PARTOS:',null,68,'PARTOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ABORTOS:',null,69,'ABORTOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CESAREAS:',null,70,'CESAREAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'METODO PLANIFICACION FLIAR:',null,71,'METODO PLANIFICACION FLIAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TIEMPO DE UTILIZACION:',null,72,'TIEMPO DE UTILIZACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FECHA ULTIMA CITOLOGIA:',null,73,'FECHA ULTIMA CITOLOGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'RESULTADO CITOLOGIA:',null,74,'RESULTADO CITOLOGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CUMPLE EL CICLO:',null,75,'CUMPLE EL CICLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'REALIZA AUTOEXAMEN DE SE MENSUALMENTE',null,76,'REALIZA AUTOEXAMEN DE SE MENSUALMENTE');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SE HA REALIZADO LA MAMOGRAFIA:',null,77,'SE HA REALIZADO LA MAMOGRAFIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FECHA DE TOMA DE MAMOGRAFIA:',null,78,'FECHA DE TOMA DE MAMOGRAFIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'RESULTADO DE LA MAMOGRAFIA:',null,79,'RESULTADO DE LA MAMOGRAFIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'VIDA SEXUAL ACTIVA:',null,80,'VIDA SEXUAL ACTIVA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CONSUMO DE GRASAS SATURADAS:',null,81,'CONSUMO DE GRASAS SATURADAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CONSUMO DE SAL:',null,82,'CONSUMO DE SAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CONSUME FRUTAS:',null,83,'CONSUME FRUTAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FRECUENCIA ACTIVIDAD FICA:',null,84,'FRECUENCIA ACTIVIDAD FICA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TIPO DE ACTIVIDAD FICA:',null,85,'TIPO DE ACTIVIDAD FICA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'DURACION ACTIVIDAD FICA:',null,86,'DURACION ACTIVIDAD FICA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CONSUMO DE PCOACTIVOS:',null,87,'CONSUMO DE PCOACTIVOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CONSUMO DE CIGARRILLO:',null,88,'CONSUMO DE CIGARRILLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FRECUENCIA DE CONSUMO DE CIGARRILLOS:',null,89,'FRECUENCIA DE CONSUMO DE CIGARRILLOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'EDAD INICIO CONSUMO DE CIGARRILLO:',null,90,'EDAD INICIO CONSUMO DE CIGARRILLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'COCE EFECTOS CIVOS:',null,91,'COCE EFECTOS CIVOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,' DE PAQUETES POR DIA:',null,92,' DE PAQUETES POR DIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CONSUMO DE ALCOHOL:',null,93,'CONSUMO DE ALCOHOL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FRECUENTA CONSUMO DE ALCOHOL:',null,94,'FRECUENTA CONSUMO DE ALCOHOL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'EXPOCION AL HUMO LEÑA/CARBON:',null,95,'EXPOCION AL HUMO LEÑA/CARBON:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SE ENTE BIEN CON SU FAMILIA:',null,96,'SE ENTE BIEN CON SU FAMILIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CUANDO TIENE PROBLEMAS ES APOYADO POR SU FAMILIA:',null,97,'CUANDO TIENE PROBLEMAS ES APOYADO POR SU FAMILIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'EN LA FAMILIA EXISTE EXPREONES DE AFECTO Y CARIÑO:',null,98,'EN LA FAMILIA EXISTE EXPREONES DE AFECTO Y CARIÑO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SE ENTE RECHAZADO POR ALGUIEN EN LA FAMILIA:',null,99,'SE ENTE RECHAZADO POR ALGUIEN EN LA FAMILIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'HA DO AGREDIDO FÍCAMENTE POR ALGUIEN DE LA FAMILIA:',null,100,'HA DO AGREDIDO FÍCAMENTE POR ALGUIEN DE LA FAMILIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'HA TENIDO IDEAS O PENSAMIENTOS SUICIDAS:',null,101,'HA TENIDO IDEAS O PENSAMIENTOS SUICIDAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SE ESTRESA FÁCILMENTE:',null,102,'SE ESTRESA FÁCILMENTE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'VIOLENCIA INTRAFAMILIAR',null,103,'VIOLENCIA INTRAFAMILIAR');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ESTADO DE ABANDO',null,104,'ESTADO DE ABANDO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'MUERTE DE ALGUN SER QUERIDO ',null,105,'MUERTE DE ALGUN SER QUERIDO ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'QUE HACE EN SU TIEMPO LIBRE:',null,106,'QUE HACE EN SU TIEMPO LIBRE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'QUE TUACIONES PERDONALES O FAMILIARES LE PREOCUPAN MAS        SU TRABAJO SU HOGAR',null,107,'QUE TUACIONES PERDONALES O FAMILIARES LE PREOCUPAN MAS        SU TRABAJO SU HOGAR');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FACTORES DE RIESCO PERSONALES O FAMILARES QUE EVIENCIEN VULNERABILIDAD',null,108,'FACTORES DE RIESCO PERSONALES O FAMILARES QUE EVIENCIEN VULNERABILIDAD');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'HIPERTEN:',null,109,'HIPERTEN:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'DIABETES:',null,110,'DIABETES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'DISLIPIDEMIA:',null,111,'DISLIPIDEMIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ENFERMEDAD CORONARIA:',null,112,'ENFERMEDAD CORONARIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'IAM',null,113,'IAM');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ENFERMEDAD ENDOCRINA:',null,114,'ENFERMEDAD ENDOCRINA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ENFERMEDAD RENAL:',null,115,'ENFERMEDAD RENAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'OBEDAD:',null,116,'OBEDAD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ENFERMEDAD VASCULAR:',null,117,'ENFERMEDAD VASCULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CA CERVIX:',null,118,'CA CERVIX:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CA COLON:',null,119,'CA COLON:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CA PROSTATA:',null,120,'CA PROSTATA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CA GASTRICO:',null,121,'CA GASTRICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CA SE:',null,122,'CA SE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'EPILEPA',null,123,'EPILEPA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'OBSERVACIONES:',null,124,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FRECUENCIA CARDIACA:',null,125,'FRECUENCIA CARDIACA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FRECUENCIA RESPIRATORIA:',null,126,'FRECUENCIA RESPIRATORIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TEMPERATURA:',null,127,'TEMPERATURA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TEN ARTERIAL',null,128,'TEN ARTERIAL');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TA SENTADO:',null,129,'TA SENTADO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TA DE PIE:',null,130,'TA DE PIE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TA ACOSTADO:',null,131,'TA ACOSTADO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'OBSERVACIONES:',null,132,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ASPECTO GENERAL:',null,133,'ASPECTO GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PESO:',null,134,'PESO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TALLA:',null,135,'TALLA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'IMC:',null,136,'IMC:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PESO ANTERIOR',null,137,'PESO ANTERIOR');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PUPILAS:',null,138,'PUPILAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'NARIZ:',null,139,'NARIZ:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'BOCA',null,140,'BOCA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CUELLO:',null,141,'CUELLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TORAX:',null,142,'TORAX:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PULMONAR:',null,143,'PULMONAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CARDIOPULMONAR:',null,144,'CARDIOPULMONAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PERIMETRO ABDOMINAL:',null,145,'PERIMETRO ABDOMINAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CADERA:',null,146,'CADERA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'INDICE CINTURA CADERA',null,147,'INDICE CINTURA CADERA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'COLUMNA:',null,148,'COLUMNA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'STEMA MUSCULOESQUELETICO:',null,149,'STEMA MUSCULOESQUELETICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PIEL:',null,150,'PIEL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'STEMA NERVIOSO CENTRAL:',null,151,'STEMA NERVIOSO CENTRAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FONDO DE OJO:',null,152,'FONDO DE OJO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TACTO RECTAL (Hombres):',null,153,'TACTO RECTAL (Hombres):');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'REFLEJO AQUILIA PRESENTE:',null,154,'REFLEJO AQUILIA PRESENTE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SENBILIDAD SUPERFICIAL:',null,155,'SENBILIDAD SUPERFICIAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SENBILIDAD VIBRATORIA:',null,156,'SENBILIDAD VIBRATORIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'NTOMATICO DE PIEL:',null,157,'NTOMATICO DE PIEL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'NTOMATICO RESPIRATORIO:',null,158,'NTOMATICO RESPIRATORIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'NDROME FEBRIL:',null,159,'NDROME FEBRIL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'NTOMATICO NERVIOSO PERIFERICO:',null,160,'NTOMATICO NERVIOSO PERIFERICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SOSPECHA DE MALTRATO FICO:',null,161,'SOSPECHA DE MALTRATO FICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SOSPECHA DE VIOLENCIA SEXUAL',null,162,'SOSPECHA DE VIOLENCIA SEXUAL');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SOSPECHA DE VIOLENCIA INTRAFAMILIAR:',null,163,'SOSPECHA DE VIOLENCIA INTRAFAMILIAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CONDUCTA AGREVA O VIOLENTA:',null,164,'CONDUCTA AGREVA O VIOLENTA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'NTOMATOLOGIA DEPREVA:',null,165,'NTOMATOLOGIA DEPREVA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'NTOMATOLOGIA DE ANEDAD:',null,166,'NTOMATOLOGIA DE ANEDAD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'IDEAS O INTENTO DE SUICIDA:',null,167,'IDEAS O INTENTO DE SUICIDA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CONSUMO DE ALCOHOL SUSTANCIAS PCOACTIVAS:',null,168,'CONSUMO DE ALCOHOL SUSTANCIAS PCOACTIVAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PENSAMIENTOS O IDEAS INCOHERENTES:',null,169,'PENSAMIENTOS O IDEAS INCOHERENTES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'VICTIMA DE DESPLAZAMIENTO',null,170,'VICTIMA DE DESPLAZAMIENTO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'APARIENCIA GENERAL:',null,171,'APARIENCIA GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ACTITUD:',null,172,'ACTITUD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ATENCION:',null,173,'ATENCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CONCIENCIA:',null,174,'CONCIENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ORIENTACION:',null,175,'ORIENTACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'LENGUAJE:',null,176,'LENGUAJE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'AFECTO:',null,177,'AFECTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'MEMORIA:',null,178,'MEMORIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PENSAMIENTO:',null,179,'PENSAMIENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'HABITO:',null,180,'HABITO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SUEÑO:',null,181,'SUEÑO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ALIMENTACION:',null,182,'ALIMENTACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'INTELIGENCIA:',null,183,'INTELIGENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'RETARDO MENTAL:',null,184,'RETARDO MENTAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'INTROSPECCION:',null,185,'INTROSPECCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PROSPECCION:',null,186,'PROSPECCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SOMATIZACIONES:',null,187,'SOMATIZACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'OBSERVACIONES:',null,188,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'Disuria:',null,189,'Disuria:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'POLIURIA:',null,190,'POLIURIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'NICTURIA:',null,191,'NICTURIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'GOTEO TERMINAL:',null,192,'GOTEO TERMINAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CHORRO CALIBRE DISMINUIDO:',null,193,'CHORRO CALIBRE DISMINUIDO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FUEZA DEL CHORRO DISMINUIDO:',null,194,'FUEZA DEL CHORRO DISMINUIDO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TACTO RECTAL:',null,195,'TACTO RECTAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'HEMATURIA:',null,196,'HEMATURIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SECRECIONES:',null,197,'SECRECIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'OBSERVACIONES:',null,198,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'OTROS',null,199,'OTROS');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'PARACLINICOS:',null,200,'PARACLINICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'Tiempo de Evolucion de Enfermedad:',null,201,'Tiempo de Evolucion de Enfermedad:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'Tratamientos Previos:',null,202,'Tratamientos Previos:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'Quien Administra el Tratamiento',null,203,'Quien Administra el Tratamiento');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'Se olvida de tomar los Medicamentos:',null,204,'Se olvida de tomar los Medicamentos:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'Descuidado con la hora de tomar Medicamentos:',null,205,'Descuidado con la hora de tomar Medicamentos:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'Cuando se encuentra bien los deja de tomar:',null,206,'Cuando se encuentra bien los deja de tomar:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,' alguna vez le caen mal los deja de tomar:',null,207,' alguna vez le caen mal los deja de tomar:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'Es alergico a Medicamentos?: Cuales',null,208,'Es alergico a Medicamentos?: Cuales');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'INTERVENCION DE MEDICINA FAMILIAR',null,209,'INTERVENCION DE MEDICINA FAMILIAR');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'HIPERTEN ARTERIAL:',null,210,'HIPERTEN ARTERIAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'DIABETES MELLITUS:',null,211,'DIABETES MELLITUS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'DESNUTRICION',null,212,'DESNUTRICION');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'SOBREPESO:',null,213,'SOBREPESO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'OBEDAD:',null,214,'OBEDAD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'ENFERMEDAD RENAL CRONICA:',null,215,'ENFERMEDAD RENAL CRONICA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TASA FILTRACION GLOMERULAR:',null,216,'TASA FILTRACION GLOMERULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'DIAGNOSTICO 1',null,217,'DIAGNOSTICO 1');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'DIAGNOSTICO 2',null,218,'DIAGNOSTICO 2');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TIPO DE DIAGSTICO:',null,219,'TIPO DE DIAGSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'CLAFICACION DE RIESGO:',null,220,'CLAFICACION DE RIESGO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'TRATAMIENTO',null,221,'TRATAMIENTO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'FARMACOLOGICO:',null,222,'FARMACOLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'VALORACION OTROS SERVICIOS:',null,223,'VALORACION OTROS SERVICIOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'Parentesco:',null,224,'Parentesco:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,83,'Telefono:',null,225,'Telefono:');



update hc_campos_Reg set nombre='CITA DE CONTROL' where id_campo=112294;
update hc_tipo_reg set url_pagina='g_historia_prevencion_enfermedades_cronicas.xhtml' where id_tipo_reg=83;











