insert into hc_tipo_reg
values(85,'HISTORIA CLINICA PLANIFICACION FAMILIAR','g_historia_clinica_planificacion_familiar',true,151,0);
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ACOMPAÑANTE:',null,0,'ACOMPAÑANTE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PARENTESCO:',null,1,'PARENTESCO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ACOMPAÑANTE:',null,2,'ACOMPAÑANTE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PARENTESCO:',null,3,'PARENTESCO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'MOTIVO CONSULTA:',null,4,'MOTIVO CONSULTA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ENFERMEDA ACTUAL:',null,5,'ENFERMEDA ACTUAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'GENERALES:',null,6,'GENERALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'DIABETES:',null,7,'DIABETES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'HIPERTENSION:',null,8,'HIPERTENSION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CARDIOPATIAS:',null,9,'CARDIOPATIAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'HEMATOPATIAS:',null,10,'HEMATOPATIAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'NEFRITIS:',null,11,'NEFRITIS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'TUMORES:',null,12,'TUMORES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'TROMBOFLEBITIS:',null,13,'TROMBOFLEBITIS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CA SENO:',null,14,'CA SENO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CA CERVIX:',null,15,'CA CERVIX:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'FUMA:',null,16,'FUMA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'MENTALES:',null,17,'MENTALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'INFECCION PELVICA:',null,18,'INFECCION PELVICA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'INFECCION CERVICAL:',null,19,'INFECCION CERVICAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'QUIRURGICOS:',null,20,'QUIRURGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'FARMACOLOGICOS:',null,21,'FARMACOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ALERGICOS:',null,22,'ALERGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'TRAUMATICOS:',null,23,'TRAUMATICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'NUTRICIONALES:',null,24,'NUTRICIONALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OTROS ANTECEDENTES:',null,25,'OTROS ANTECEDENTES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OBSERVACIONES:',null,26,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'MENARQUIA/ESPERMARCA:',null,27,'MENARQUIA/ESPERMARCA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'SEXARQUIA:',null,28,'SEXARQUIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'HABITOS SEXUALES:',null,29,'HABITOS SEXUALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'NO DE COMPAÑEROS:',null,30,'NO DE COMPAÑEROS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'FLUJOS VAGINALES:',null,31,'FLUJOS VAGINALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'FECHA ULTIMA MENSTRUACION:',null,32,'FECHA ULTIMA MENSTRUACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CICLOS MENSTRUALES:',null,33,'CICLOS MENSTRUALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'TRASTORNOS MENSTRUALES:',null,34,'TRASTORNOS MENSTRUALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'METODO PLANIFICACION FLIAR:',null,35,'METODO PLANIFICACION FLIAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'FECHA ULTIMA CITOLOGIA:',null,36,'FECHA ULTIMA CITOLOGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'RESULTADO CITOLOGIA:',null,37,'RESULTADO CITOLOGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'INF. TRANSMISION SEXUAL:',null,38,'INF. TRANSMISION SEXUAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ITS TRATAMIENTO:',null,39,'ITS TRATAMIENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'GESTAS:',null,40,'GESTAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PARTOS:',null,41,'PARTOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ABORTOS:',null,42,'ABORTOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CESREAS:',null,43,'CESREAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'VIVOS:',null,44,'VIVOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'MUERTOS:',null,45,'MUERTOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'NORTINATOS:',null,46,'NORTINATOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'HISTORIA DE EMBARAZOS ANTERIORES:',null,47,'HISTORIA DE EMBARAZOS ANTERIORES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'HISTORIA ANTICONCEPCIONAL:',null,48,'HISTORIA ANTICONCEPCIONAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'GENERAL:',null,49,'GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CABEZA:',null,50,'CABEZA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OJOS:',null,51,'OJOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'NARIZ:',null,52,'NARIZ:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OIDOS:',null,53,'OIDOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OROFAFINGE:',null,54,'OROFAFINGE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CUELLO:',null,55,'CUELLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'RESPIRATORIO:',null,56,'RESPIRATORIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'NEUROLOGICO:',null,57,'NEUROLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ENDOCRINO:',null,58,'ENDOCRINO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'MUSCULO ESQUELETICO:',null,59,'MUSCULO ESQUELETICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'HEMATOPOYETICP:',null,60,'HEMATOPOYETICP:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'LINFORRETICULAR:',null,61,'LINFORRETICULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PSIQUIATRICOS:',null,62,'PSIQUIATRICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PIEL Y FANERA:',null,63,'PIEL Y FANERA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ARTICULAR:',null,64,'ARTICULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CARDIOVASCULAR:',null,65,'CARDIOVASCULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'GASTRO - INTESTINAL:',null,66,'GASTRO - INTESTINAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'GINECOLOGICO:',null,67,'GINECOLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'UROLOGICO:',null,68,'UROLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OTROS:',null,69,'OTROS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'FRECUENCIA CARDIACA:',null,70,'FRECUENCIA CARDIACA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'FRECUENCIA RESPIRATORIA:',null,71,'FRECUENCIA RESPIRATORIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'TEMPERATURA:',null,72,'TEMPERATURA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PULSO:',null,73,'PULSO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'TENSION ARTERIAL:',null,74,'TENSION ARTERIAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PRIMARIA:',null,75,'PRIMARIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'SECUNDARIA:',null,76,'SECUNDARIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'UNIVERSITARIA:',null,77,'UNIVERSITARIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'TECNOLOGICA:',null,78,'TECNOLOGICA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OTROS:',null,79,'OTROS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ASPECTO GENERAL:',null,80,'ASPECTO GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PESO:',null,81,'PESO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'TALLA:',null,82,'TALLA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'IMCA:',null,83,'IMCA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CABEZA:',null,84,'CABEZA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OIOS',null,85,'OIOS');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OTORRINOLARINGOLOGIA:',null,86,'OTORRINOLARINGOLOGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CUELLO:',null,87,'CUELLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'TORAX:',null,88,'TORAX:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PULMONAR:',null,89,'PULMONAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CARDIOVASCULAR:',null,90,'CARDIOVASCULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PIEL:',null,91,'PIEL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ABDOMEN:',null,92,'ABDOMEN:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'GENITOURINARIO:',null,93,'GENITOURINARIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'EXTREMIDADES:',null,94,'EXTREMIDADES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'SISTEMA MUSCULOESQUELECTICO:',null,95,'SISTEMA MUSCULOESQUELECTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'NEUROLOGICO:',null,96,'NEUROLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'SINTOMATICO DE PIEL:',null,97,'SINTOMATICO DE PIEL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'SINTOMATICO RESPIRATORIO:',null,98,'SINTOMATICO RESPIRATORIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'SINDROME FEBRIL:',null,99,'SINDROME FEBRIL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'SINTOMATICO NERVIOSO PERIFERICO:',null,100,'SINTOMATICO NERVIOSO PERIFERICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OBSERVACIONES:',null,101,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CEFALEAS:',null,102,'CEFALEAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PERFUSION:',null,103,'PERFUSION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'MANCHAS EN LA PIEL:',null,104,'MANCHAS EN LA PIEL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'MAMAS NORMALES:',null,105,'MAMAS NORMALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'UTERO Y ANEXOS NORMALES:',null,106,'UTERO Y ANEXOS NORMALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CERVIC NORMAL:',null,107,'CERVIC NORMAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'SINTOMAS URINARIOS:',null,108,'SINTOMAS URINARIOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'FLUJO VAGINAL:',null,109,'FLUJO VAGINAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'DOLOR BAJO VIENTRE:',null,110,'DOLOR BAJO VIENTRE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'EDEMAS:',null,111,'EDEMAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'VARICES:',null,112,'VARICES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'MAREOS:',null,113,'MAREOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'SIGNOS DE EMBARAZO:',null,114,'SIGNOS DE EMBARAZO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'TRASTORNO MENSTRUALES:',null,115,'TRASTORNO MENSTRUALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CAMBIOS DE COMPORTAMIENTO:',null,116,'CAMBIOS DE COMPORTAMIENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'SATISFACCION CON EL METODO:',null,117,'SATISFACCION CON EL METODO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CAMBIO DE METODO:',null,118,'CAMBIO DE METODO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'EXPULSION DISPOTIVOS:',null,119,'EXPULSION DISPOTIVOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'RIESGO REPRODUCTIVO:',null,120,'RIESGO REPRODUCTIVO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CITOLOGIA:',null,121,'CITOLOGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OTROS HALLAZGOS:',null,122,'OTROS HALLAZGOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'APARIENCIA GENERAL:',null,123,'APARIENCIA GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ACTITUD:',null,124,'ACTITUD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ATENCION:',null,125,'ATENCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CONCIENCIA:',null,126,'CONCIENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ORIENTACION:',null,127,'ORIENTACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'LENGUAJE:',null,128,'LENGUAJE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'AFECTO:',null,129,'AFECTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'MEMORIA:',null,130,'MEMORIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PENSAMIENTO:',null,131,'PENSAMIENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'HABITO:',null,132,'HABITO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'SUEÑO:',null,133,'SUEÑO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'ALIMENTACION:',null,134,'ALIMENTACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'INTELIGENCIA:',null,135,'INTELIGENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'RETARDADO MENTAL:',null,136,'RETARDADO MENTAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'INTROSPECCION:',null,137,'INTROSPECCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'SOMATIZACIONES:',null,138,'SOMATIZACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OBSERVACIONES:',null,139,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'INTERVENCION DE MEDICINA FAMILIAR:',null,140,'INTERVENCION DE MEDICINA FAMILIAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PRUEBA DE EMBARAZO:',null,141,'PRUEBA DE EMBARAZO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PATOLOGIA CERVICO',null,142,'PATOLOGIA CERVICO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'FROTIS DE FLUJO:',null,143,'FROTIS DE FLUJO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'RIESGO REPRODUCTIVO:',null,144,'RIESGO REPRODUCTIVO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PILDORA:',null,145,'PILDORA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OBSERVACIONES:',null,146,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'INTERVENCION DE MEDICINA FAMILIAR:',null,147,'INTERVENCION DE MEDICINA FAMILIAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'DESCRIPCION DEL PROCEDIMIENTO',null,148,'DESCRIPCION DEL PROCEDIMIENTO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'DIAGNOSTICO:',null,149,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'TIPO DE DIAGNOSTICO',null,150,'TIPO DE DIAGNOSTICO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'TUMORES',null,151,'TUMORES');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'MENTALES',null,152,'MENTALES');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'OBSERVACIONES',null,153,'OBSERVACIONES');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'HIPERTENSION',null,154,'HIPERTENSION');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'DIABETES',null,155,'DIABETES');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'CARDIOPATIAS',null,156,'CARDIOPATIAS');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'HEPATOPATIAS',null,157,'HEPATOPATIAS');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,85,'PROSPECCION',null,158,'PROSPECCION');

update hc_tipo_reg set cant_campos=159  where id_Tipo_reg=85;

