insert into hc_tipo_reg values(88,'CRECIMIENTO Y DESARROLLO','s_crecimiento_desarrollo.xhtml',true,221,0);
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'MOTIVO DE CONSULTA:',null,0,'MOTIVO DE CONSULTA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ENFERMEDAD ACTUAL:',null,1,'ENFERMEDAD ACTUAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PATOLOGICOS:',null,2,'PATOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'QUIRURGICOS:',null,3,'QUIRURGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TOXICOS:',null,4,'TOXICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TRAUMATICOS:',null,5,'TRAUMATICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ALERGICOS:',null,6,'ALERGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TRASTORNO DELIRANTE:',null,7,'TRASTORNO DELIRANTE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'DEPRESIVOS MAYORES:',null,8,'DEPRESIVOS MAYORES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'EPISODIOS DE MANIA:',null,9,'EPISODIOS DE MANIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'INTENTOS DE SUICIDIO:',null,10,'INTENTOS DE SUICIDIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TRANSTORNOS DE PERSONALIDAD:',null,11,'TRANSTORNOS DE PERSONALIDAD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ESQUIZOFRENIA:',null,12,'ESQUIZOFRENIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'EPILEPSIA:',null,13,'EPILEPSIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'DIABETES:',null,14,'DIABETES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'HIPERTENSION:',null,15,'HIPERTENSION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CANCER:',null,16,'CANCER:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OTROS:',null,17,'OTROS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'No HERMANOS VIVOS:',null,18,'No HERMANOS VIVOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'No HERMANOS MUERTOS:',null,19,'No HERMANOS MUERTOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'MENORES DE 5 AÑOS:',null,20,'MENORES DE 5 AÑOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ATENCION PRENATAL:',null,21,'ATENCION PRENATAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'EMBARAZO DESEADO:',null,22,'EMBARAZO DESEADO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'EMBARASO NORMAL:',null,23,'EMBARASO NORMAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'EDAD DE LA MADRE AL NACER EL NIÑO:',null,24,'EDAD DE LA MADRE AL NACER EL NIÑO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'MESES DE GESTACION AL NACER EL NIÑO:',null,25,'MESES DE GESTACION AL NACER EL NIÑO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OBSERVACIONES:',null,26,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PARTO INSTITUCIONAL:',null,27,'PARTO INSTITUCIONAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'MODALIDAD DEL PARTO:',null,28,'MODALIDAD DEL PARTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PRESENTACION CEFALICA:',null,29,'PRESENTACION CEFALICA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PRODUCTO UNICO:',null,30,'PRODUCTO UNICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ESTUVO EN ENCUBADORA:',null,31,'ESTUVO EN ENCUBADORA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'RECIBIO FOTOTERAPIA:',null,32,'RECIBIO FOTOTERAPIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'LAC. MATERNA 1A HORA',null,33,'LAC. MATERNA 1A HORA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PESO AL NACER:',null,34,'PESO AL NACER:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TALLA AL NACER',null,35,'TALLA AL NACER');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TIPO BIOLOGICO   UNICA',null,36,'TIPO BIOLOGICO   UNICA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'FIEBRE AMARILLA:',null,37,'FIEBRE AMARILLA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'HEPATITIS:',null,38,'HEPATITIS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PENTAVALENTE:',null,39,'PENTAVALENTE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'POLIO:',null,40,'POLIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'NEUMOCOCO:',null,41,'NEUMOCOCO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ROTAVIRUS:',null,42,'ROTAVIRUS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'FIEBRE AMARILLA:',null,43,'FIEBRE AMARILLA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TRIPLEVIRAL:',null,44,'TRIPLEVIRAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'DPT:',null,45,'DPT:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SARAMPION:',null,46,'SARAMPION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TOSFERINA:',null,47,'TOSFERINA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'DIFTERINA:',null,48,'DIFTERINA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'POLIO:',null,49,'POLIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PAROTIDITIS:',null,50,'PAROTIDITIS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'RUBEOLA:',null,51,'RUBEOLA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TUBERCULOSIS:',null,52,'TUBERCULOSIS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ALERGIAS:',null,53,'ALERGIAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'HEPATITIS:',null,54,'HEPATITIS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'FIEBRE REUMATICA:',null,55,'FIEBRE REUMATICA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'E.D.A. (ULTIMOS DOS MESES)',null,56,'E.D.A. (ULTIMOS DOS MESES)');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'I.R.A. (ULTIMOS DOS MESES)',null,57,'I.R.A. (ULTIMOS DOS MESES)');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ACCIDENTES (ULTIMOS DOS MESES)',null,58,'ACCIDENTES (ULTIMOS DOS MESES)');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SINDOMES CONVULSIVOS (ULTIMO AÑO)',null,59,'SINDOMES CONVULSIVOS (ULTIMO AÑO)');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OTROS CUAL ?',null,60,'OTROS CUAL ?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ANTECEDENTES QUIRURGICOS:',null,61,'ANTECEDENTES QUIRURGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OBSERVACIONES:',null,62,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'LACTANCIA MATERNA:',null,63,'LACTANCIA MATERNA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ALIMENTACION COMPLEMENTARIA:',null,64,'ALIMENTACION COMPLEMENTARIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'EDAD DEL NIÑO AL DESTETE:',null,65,'EDAD DEL NIÑO AL DESTETE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'EDAD DEL NIÑO AL INICIAR ALIMENTACIN COMPLEMENTARIA:',null,66,'EDAD DEL NIÑO AL INICIAR ALIMENTACIN COMPLEMENTARIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'FRUTAS NO ACIDAS:',null,67,'FRUTAS NO ACIDAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CEREALES:',null,68,'CEREALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'VISCERAS:',null,69,'VISCERAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'MEZCLAS VEGETALES:',null,70,'MEZCLAS VEGETALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'HORTALIZAS Y VERDURAS:',null,71,'HORTALIZAS Y VERDURAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'RAICES Y TUBERCULOS:',null,72,'RAICES Y TUBERCULOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CARNES:',null,73,'CARNES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'HUEVOS:',null,74,'HUEVOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'LEGUMINOSAS:',null,75,'LEGUMINOSAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'LECHE DE VACA Y DERIBADOS:',null,76,'LECHE DE VACA Y DERIBADOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'AZUCARES Y SUBPRODUCTOS:',null,77,'AZUCARES Y SUBPRODUCTOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'GRASAS:',null,78,'GRASAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OBSERVACIONES:',null,79,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'GENERAL:',null,80,'GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CABEZA:',null,81,'CABEZA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OJOS:',null,82,'OJOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'NARIZ:',null,83,'NARIZ:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OIDOS:',null,84,'OIDOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OROFAFINGE:',null,85,'OROFAFINGE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CUELLO:',null,86,'CUELLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'RESPIRATORIO:',null,87,'RESPIRATORIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'NEUROLOGICO:',null,88,'NEUROLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ENDOCRINO:',null,89,'ENDOCRINO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'MUSCULO(ESQUELETICO:',null,90,'MUSCULO(ESQUELETICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'HEMATOPOYETICO:',null,91,'HEMATOPOYETICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'LINFORRETICULAR:',null,92,'LINFORRETICULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PSIQUIATRICOS:',null,93,'PSIQUIATRICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PIEL Y FANERAS:',null,94,'PIEL Y FANERAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ARTICULAR:',null,95,'ARTICULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CARDIOVASCULAR:',null,96,'CARDIOVASCULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'GASTRO - INTESTINAL:',null,97,'GASTRO - INTESTINAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'UROLOGICO:',null,98,'UROLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OTROS:',null,99,'OTROS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'FRECUENCIA CARDIACA:',null,100,'FRECUENCIA CARDIACA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'FRECUENCIA RESPIRATORIA:',null,101,'FRECUENCIA RESPIRATORIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TEMPERATURA:',null,102,'TEMPERATURA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PULSO:',null,103,'PULSO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TENSION ARTERIA',null,104,'TENSION ARTERIA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ASPECTO GENERAL:',null,105,'ASPECTO GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PESO:',null,106,'PESO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TALLA:',null,107,'TALLA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'IMC:',null,108,'IMC:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PERIMETRO CEFALICO:',null,109,'PERIMETRO CEFALICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CABEZA:',null,110,'CABEZA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OJOS:',null,111,'OJOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OIDOS:',null,112,'OIDOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'NARIZ:',null,113,'NARIZ:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OBSERVACIONES:',null,114,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OTORRINOLARINGOLOGIA:',null,115,'OTORRINOLARINGOLOGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CUELLO:',null,116,'CUELLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TORAX:',null,117,'TORAX:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PULMONAR:',null,118,'PULMONAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CARDIOVASCULAR:',null,119,'CARDIOVASCULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ABDOMEN:',null,120,'ABDOMEN:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'GENITOURINARIO:',null,121,'GENITOURINARIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'EXTREMIDADES:',null,122,'EXTREMIDADES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PIEL:',null,123,'PIEL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SINTOMATICO DE PIEL:',null,124,'SINTOMATICO DE PIEL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SINTOMATICO RESPIRATORIO:',null,125,'SINTOMATICO RESPIRATORIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SINDROME FEBRIL:',null,126,'SINDROME FEBRIL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SISTEMA MUSCULOESQUELETICO:',null,127,'SISTEMA MUSCULOESQUELETICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SISTEMA NERVIOSO:',null,128,'SISTEMA NERVIOSO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ANO:',null,129,'ANO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'VALORAC. DESARROLLO MOTORA:',null,130,'VALORAC. DESARROLLO MOTORA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'VALORAC. DESARROLLO ADAPTATIVA:',null,131,'VALORAC. DESARROLLO ADAPTATIVA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'VALORAC. DESARROLLO LENGUAJE:',null,132,'VALORAC. DESARROLLO LENGUAJE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'VALORAC. DESARROLLO PERSONAL SOCIAL:',null,133,'VALORAC. DESARROLLO PERSONAL SOCIAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CURVA PESO:',null,134,'CURVA PESO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CURVA TALLA:',null,135,'CURVA TALLA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ESTADO NUTRICIONAL:',null,136,'ESTADO NUTRICIONAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OBSERVACIONES:',null,137,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'MALTRATO FISICO',null,138,'MALTRATO FISICO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SOSPECHA DE VIOLENCIA SEXUAL:',null,139,'SOSPECHA DE VIOLENCIA SEXUAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SOSPECHA DE VIOLENCIA INTRAFAMILIAR:',null,140,'SOSPECHA DE VIOLENCIA INTRAFAMILIAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CONDUCTA AGRESIVA O VIOLENTA:',null,141,'CONDUCTA AGRESIVA O VIOLENTA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SINTOMATOLOGIA DEPRESIVA:',null,142,'SINTOMATOLOGIA DEPRESIVA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SINTOMATOLOGIA DE ANSIEDAD:',null,143,'SINTOMATOLOGIA DE ANSIEDAD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'IDEAS O INTENTO DE SUICIDA:',null,144,'IDEAS O INTENTO DE SUICIDA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CONSUMO DE ALCOHOL SUSTANCIAS PSICOACTIVAS:',null,145,'CONSUMO DE ALCOHOL SUSTANCIAS PSICOACTIVAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PENSAMIENTOS O IDEAS INCOHERENTES:',null,146,'PENSAMIENTOS O IDEAS INCOHERENTES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'VICTIMA DE DESPLAZAMIENTO',null,147,'VICTIMA DE DESPLAZAMIENTO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'APARIENCIA GENERAL:',null,148,'APARIENCIA GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ACTITUD:',null,149,'ACTITUD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ATENCION:',null,150,'ATENCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CONCIENCIA:',null,151,'CONCIENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ORIENTACION:',null,152,'ORIENTACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'LENGUAJE:',null,153,'LENGUAJE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'AFECTO:',null,154,'AFECTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'MEMORIA:',null,155,'MEMORIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PENSAMIENTO:',null,156,'PENSAMIENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'HABITO:',null,157,'HABITO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SUEÑO:',null,158,'SUEÑO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'ALIMENTACION:',null,159,'ALIMENTACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'INTELIGENCIA:',null,160,'INTELIGENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'RETARDO MENTAL:',null,161,'RETARDO MENTAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'INTROSPECCION:',null,162,'INTROSPECCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PROSPECCION:',null,163,'PROSPECCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SOMATIZACIONES:',null,164,'SOMATIZACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OBSERVACIONES:',null,165,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'DIAGNOSTICO:',null,166,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PRESENTA ALCUN SINTOMA ANTES DE INICIAL LA CRISIS(AURA) COMO MIEDOS, DESVIACION DE CABEZA',null,167,'PRESENTA SINTOMA ANTES DE INICIAL LA CRISIS(AURA) COMO MIEDOS, DESVIACION DE CABEZA U OJOS HACIA UN LADO,HORMIGUEO,INCAPACIDAD PARA HABLAR, VISION BORROSA?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PIERDE LA CONCIENCIA DURANTE LOS EPISODIOS?',null,168,'PIERDE LA CONCIENCIA DURANTE LOS EPISODIOS?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PRESENTA MIRADA FIJA, PARPADEO O FALTA DE RESPUESTA DURANTE EL EPISODIO?',null,169,'PRESENTA MIRADA FIJA, PARPADEO O FALTA DE RESPUESTA DURANTE EL EPISODIO?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PRESENTA MOVIMIENTOS INVOLUNTARIOS ANORMALES, INCONTROLADOS, SACUDIDAS O SOBRESALTOS MUSCULARES?.',null,170,'PRESENTA MOVIMIENTOS INVOLUNTARIOS ANORMALES,             INCONTROLADOS, SACUDIDAS O SOBRESALTOS MUSCULARES?.');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PRESENTA AUTOMATISMOS COMO DEGLUCION, CHUPETEO, SABOREO O MOVIMIENTOS RESPETIVOS SIN PROPOSITOS ',null,171,'PRESENTA AUTOMATISMOS COMO DEGLUCION, CHUPETEO, SABOREO   O MOVIMIENTOS RESPETIVOS SIN PROPOSITOS CON LAS MANOS?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PRESENTA SINTOMAS POST-ICTALES?',null,172,'PRESENTA SINTOMAS POST-ICTALES?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CUANTO DE DURAN LAS CIRIS',null,173,'CUANTO DE DURAN LAS CIRIS');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CUANTOS EPISODIOS HA PRESENTADO EN LOS ULTIMOS 12 MESES?',null,174,'CUANTOS EPISODIOS HA PRESENTADO EN LOS ULTIMOS 12 MESES?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CUANDO FUE LA ULTIMA CRISIS?',null,175,'CUANDO FUE LA ULTIMA CRISIS?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'LAS CRISIS OCURREN SOLO CON FIEBRE?',null,176,'LAS CRISIS OCURREN SOLO CON FIEBRE?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'LOS EPISODIOS OCURREN SOLO ASOCIADOS A LLANTO,ALIMENTACION, ANSIEDAD O TRAUMAS LEVES DE CRANEO?',null,177,'LOS EPISODIOS OCURREN SOLO ASOCIADOS A LLANTO,        ALIMENTACION, ANSIEDAD O TRAUMAS LEVES DE CRANEO?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TIENE ALGUN ANTECEDENTE DE IMPORTANCIA?',null,178,'TIENE ALGUN ANTECEDENTE DE IMPORTANCIA?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SE ENCUENTRA DURANTE LA CONSULTA EN CRISIS?',null,179,'SE ENCUENTRA DURANTE LA CONSULTA EN CRISIS?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'NIVEL DE CONCIENCIA:',null,180,'NIVEL DE CONCIENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PRESENTA DURANTE LA CONSULTA 2 O MAS EPISODIOS DE  CRISIS SIN RECUPERACION DE LA',null,181,'PRESENTA DURANTE LA CONSULTA 2 O MAS EPISODIOS DE  CRISIS SIN RECUPERACION DE LA CONCIENCIA ENTRE ELLOS');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SIGNOS Y SINTOMAS NEUROLOGICOS DE APARICION AGUDA O PROGRESIVA:',null,182,'SIGNOS Y SINTOMAS NEUROLOGICOS DE APARICION AGUDA O PROGRESIVA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'DIAGNOSTICO:',null,183,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TIENE CONTACTO CON PERSONAS CON TUBERCULOSIS:',null,184,'TIENE CONTACTO CON PERSONAS CON TUBERCULOSIS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TIENE TOS PERSISTENTE POR MAS DE 21 DIAS:',null,185,'TIENE TOS PERSISTENTE POR MAS DE 21 DIAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TIENE FIEBRE MAS DE 14 DIAS ',null,186,'TIENE FIEBRE MAS DE 14 DIAS ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'HA PERDIDO O NO HA GANADO PESO EN LOS ULTIMOS 3 MESES',null,187,'HA PERDIDO O NO HA GANADO PESO EN LOS ULTIMOS 3 MESES');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TIENE ADENOMEGALIA MAYOR DE 2x2 cm DESDE HACE MAS DE 4 SEM.',null,188,'TIENE ADENOMEGALIA MAYOR DE 2x2 cm DESDE HACE MAS DE 4 SEM.');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PRIMERA CONSULTA?',null,189,'PRIMERA CONSULTA?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PPD FECHA APLICACION',null,190,'PPD FECHA APLICACION');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'RX TORAX:',null,191,'RX TORAX:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SIGNO GENERAL DE PELIGRO:',null,192,'SIGNO GENERAL DE PELIGRO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'RIGIDEX EN LA NUCA',null,193,'RIGIDEX EN LA NUCA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'COMPORTAMIENTO ANORMAL RECIDENTE',null,194,'COMPORTAMIENTO ANORMAL RECIDENTE');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TIRAJE SUBCOSTAL',null,195,'TIRAJE SUBCOSTAL');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'INFECCION POR VIH/SIDA',null,196,'INFECCION POR VIH/SIDA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'DESNUTRICION GRAVE',null,197,'DESNUTRICION GRAVE');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'CULTIVO DE JUGO GASTRICO POSITIVO PARA TB',null,198,'CULTIVO DE JUGO GASTRICO POSITIVO PARA TB');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'BACILOSCOPIA POSITIVA PARA TB',null,199,'BACILOSCOPIA POSITIVA PARA TB');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'HISOPATOLOGIA POSITIVA PARA TB',null,200,'HISOPATOLOGIA POSITIVA PARA TB');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PCR POSITIVA PARA TB',null,201,'PCR POSITIVA PARA TB');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OBSERVACIONES',null,202,'OBSERVACIONES');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'DIAGNOSTICO:',null,203,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'HA TENIDO FIEBRE POR MAS DE 7 DIAS Y/O SUDORACION IMPORTANTE?',null,204,'HA TENIDO FIEBRE POR MAS DE 7 DIAS Y/O SUDORACION IMPORTANTE?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PRESENTA RECIENTEMENTE DOLOR DE CABEZA QUE HA IDO EN AUMENTO?',null,205,'PRESENTA RECIENTEMENTE DOLOR DE CABEZA QUE HA IDO EN AUMENTO?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'DESPIERTA EL DOLOR DE CABEZA AL NIÑO EN LA NOCHE?',null,206,'DESPIERTA EL DOLOR DE CABEZA AL NIÑO EN LA NOCHE?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SE ACOMPAÑA DE ALGUN OTRO SINTOMA COMO VOMITO?',null,207,'SE ACOMPAÑA DE ALGUN OTRO SINTOMA COMO VOMITO?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PRESENTA DOLORES DE HUESOS EN EL ULTIMO MES',null,208,'PRESENTA DOLORES DE HUESOS EN EL ULTIMO MES');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'HA PRESENTADO CAMBIOS COMO PERDIDA DE APETITO PERDIDA)     DE PESO O FATIGA EN LOS ULTIMOS 3 MESES',null,209,'HA PRESENTADO CAMBIOS COMO PERDIDA DE APETITO PERDIDA)     DE PESO O FATIGA EN LOS ULTIMOS 3 MESES');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PETEQUIAS, EQUIMOSIS O SANGRADO',null,210,'PETEQUIAS, EQUIMOSIS O SANGRADO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PALIDEX PALMAR Y/O CONJUNTIVAL:',null,211,'PALIDEX PALMAR Y/O CONJUNTIVAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'GANGLIOS TAMAÑO > 2,5 CM',null,212,'GANGLIOS TAMAÑO > 2,5 CM');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'SIGNOS Y SINTOMAS NEUROLOGICOS FOCALES     DE APARICION AGUDA O PROGRESIVA:',null,213,'SIGNOS Y SINTOMAS NEUROLOGICOS FOCALES     DE APARICION AGUDA O PROGRESIVA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'PRESENCIA DE MASA PALPABLE ABDOMINAL',null,214,'PRESENCIA DE MASA PALPABLE ABDOMINAL');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'HEPATOMEGALIA Y/O ESPLENOMEGALIA',null,215,'HEPATOMEGALIA Y/O ESPLENOMEGALIA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'AUMENTO DE VOLUMEN EN ALGUNA REGION DEL CUERPO',null,216,'AUMENTO DE VOLUMEN EN ALGUNA REGION DEL CUERPO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'DIAGNOSTICO:',null,217,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'TIPO DE DIAGNOSTICO:',null,218,'TIPO DE DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'OBSERVACIONES:',null,219,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,88,'REMISION:',null,220,'REMISION:');
