insert into hc_tipo_reg
values(84,'AIEPI MENOR DE DOS MESES PyP','g_aiepi_menor_2_meses',true,193,0);
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ACOMPAÑANTE:',null,0,'ACOMPAÑANTE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PARENTESCO:',null,1,'PARENTESCO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'MOTIVO CONSULTA:',null,2,'MOTIVO CONSULTA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'GENERALES:',null,3,'GENERALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PATOLOGICOS:',null,4,'PATOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ALERGICOS:',null,5,'ALERGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'OBSTETRICOS:',null,6,'OBSTETRICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'GINECOLOGICOS:',null,7,'GINECOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'COMO FUE EL EMBARAZO/DURACION:',null,8,'COMO FUE EL EMBARAZO/DURACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'COMO FUE EL PARTO:',null,9,'COMO FUE EL PARTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CUANTO PESO AL NACER:',null,10,'CUANTO PESO AL NACER:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PROBLEMAS DESPUES DEL NAC:',null,11,'PROBLEMAS DESPUES DEL NAC:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'QUE ENFERMEDADES HAS TENIDO:',null,12,'QUE ENFERMEDADES HAS TENIDO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TRAUMATICOS:',null,13,'TRAUMATICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'INMUNOLOGICOS:',null,14,'INMUNOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ALERGICOS:',null,15,'ALERGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'FARMACOLOGICOS:',null,16,'FARMACOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TOXICOS:',null,17,'TOXICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PARTO INSTITUCIONAL:',null,18,'PARTO INSTITUCIONAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PROBABILIDAD DEL PARTO:',null,19,'PROBABILIDAD DEL PARTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PRESENTACION CEFALICA:',null,20,'PRESENTACION CEFALICA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PRODUCTO UNICO:',null,21,'PRODUCTO UNICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ESTUVO EN ENCUBADORA:',null,22,'ESTUVO EN ENCUBADORA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RECIBIO FOTOTERAPIA:',null,23,'RECIBIO FOTOTERAPIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'LAC. MATERNA LA HORA:',null,24,'LAC. MATERNA LA HORA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PESO AL NACER GRAMOS:',null,25,'PESO AL NACER GRAMOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TALLA AL NACER:',null,26,'TALLA AL NACER:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'GENERAL:',null,27,'GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CABEZA:',null,28,'CABEZA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'OJOS:',null,29,'OJOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'NARIZ:',null,30,'NARIZ:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'OIDOS:',null,31,'OIDOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'OROFAFINGE:',null,32,'OROFAFINGE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CUELLO:',null,33,'CUELLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RESPIRATORIO:',null,34,'RESPIRATORIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'NEUROLOGICO:',null,35,'NEUROLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ENDOCRINO:',null,36,'ENDOCRINO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'MUSCULO(ESQUELECTICO):',null,37,'MUSCULO(ESQUELECTICO):');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'HEMATOPOYETICO:',null,38,'HEMATOPOYETICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'LINFORRETICULAR:',null,39,'LINFORRETICULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PSIQUIATRICOS:',null,40,'PSIQUIATRICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PIEL Y FANERAS:',null,41,'PIEL Y FANERAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ARTICULAR:',null,42,'ARTICULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CARDIOVASCULAR:',null,43,'CARDIOVASCULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'GASTRO - INTESTINAL:',null,44,'GASTRO - INTESTINAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'GINECOLOGICO:',null,45,'GINECOLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'UROLOGICO:',null,46,'UROLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'OTROS:',null,47,'OTROS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'FRECUENCIA CARDIACA:',null,48,'FRECUENCIA CARDIACA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'FRECUENCIA RESPIRATORIA:',null,49,'FRECUENCIA RESPIRATORIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TEMPERATURA:',null,50,'TEMPERATURA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TENSION ARTERIAL:',null,51,'TENSION ARTERIAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SATURACION DE OXIGENO:',null,52,'SATURACION DE OXIGENO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ASPECTO GENERAL:',null,53,'ASPECTO GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PESO AL NACER:',null,54,'PESO AL NACER:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PESO:',null,55,'PESO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TALLA:',null,56,'TALLA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'IMC:',null,57,'IMC:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PERIMETRO CEFALICO:',null,58,'PERIMETRO CEFALICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'EL NIÑO PRESENTA APNEA:',null,59,'EL NIÑO PRESENTA APNEA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SINTOMATICO DE PIEL:',null,60,'SINTOMATICO DE PIEL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SINTOMATICO RESPIRATORIO:',null,61,'SINTOMATICO RESPIRATORIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SINDROME FEBRIL:',null,62,'SINDROME FEBRIL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SINTOMATICO NERVIOSO PERFIFERICO:',null,63,'SINTOMATICO NERVIOSO PERFIFERICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SUPURACION DE OIDO:',null,64,'SUPURACION DE OIDO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CABEZA:',null,65,'CABEZA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'OJOS:',null,66,'OJOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'OIDOS:',null,67,'OIDOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'NARIZ:',null,68,'NARIZ:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'BOCA:',null,69,'BOCA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'OTORRINOLARINCOLOGIA:',null,70,'OTORRINOLARINCOLOGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CUELLO:',null,71,'CUELLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TORAX:',null,72,'TORAX:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PULMONAR:',null,73,'PULMONAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CARDIOVASCULAR:',null,74,'CARDIOVASCULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ABDOMEN:',null,75,'ABDOMEN:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'EXTREMIDADES:',null,76,'EXTREMIDADES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'COLUMNA:',null,77,'COLUMNA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SISTEMA MUSCULOESQUELETICO:',null,78,'SISTEMA MUSCULOESQUELETICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PIEL:',null,79,'PIEL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'OBSERVACIONES:',null,80,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SOSPECHA DE MALTRATO FISICO:',null,81,'SOSPECHA DE MALTRATO FISICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SOPECHA DE VIOLENCIA SEXUAL:',null,82,'SOPECHA DE VIOLENCIA SEXUAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SOSPECHA DE VIOLENCIA INTRAFAMILIAR:',null,83,'SOSPECHA DE VIOLENCIA INTRAFAMILIAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CONDUCTA AGRESIVA O VIOLENTA:',null,84,'CONDUCTA AGRESIVA O VIOLENTA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SINTOMATOLOGIA DEPRESIVA:',null,85,'SINTOMATOLOGIA DEPRESIVA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SINTOMATOLOGIA DE ANSIEDAD:',null,86,'SINTOMATOLOGIA DE ANSIEDAD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'IDEAS O INTENTO DE SUICIDA:',null,87,'IDEAS O INTENTO DE SUICIDA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CONSUMO DE ALCOHOL SUSTANCIAS:',null,88,'CONSUMO DE ALCOHOL SUSTANCIAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PENSAMIENTOS O IDEAS INCOHERENTES:',null,89,'PENSAMIENTOS O IDEAS INCOHERENTES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'VICTIMA DE DESPLAZAMIENTO',null,90,'VICTIMA DE DESPLAZAMIENTO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'APARIENCIA GENERAL:',null,91,'APARIENCIA GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ACTITUD:',null,92,'ACTITUD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ATENCION:',null,93,'ATENCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CONCIENCIA:',null,94,'CONCIENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ORIENTACION:',null,95,'ORIENTACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'LENGUAJE:',null,96,'LENGUAJE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'AFECTO:',null,97,'AFECTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'MEMORIA:',null,98,'MEMORIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PENSAMIENTO:',null,99,'PENSAMIENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'HABITO:',null,100,'HABITO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SUEÑO:',null,101,'SUEÑO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ALIMENTACION:',null,102,'ALIMENTACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'INTELIGENCIA:',null,103,'INTELIGENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RETARDO MENTAL:',null,104,'RETARDO MENTAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'INTROSPECCION:',null,105,'INTROSPECCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PROSPECCION:',null,106,'PROSPECCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SOMATIZACIONES:',null,107,'SOMATIZACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'OBSERVACIONES:',null,108,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'DIAGNOSTICO:',null,109,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'¿PUEDE BEBER O TOMAR EL PECHO?',null,110,'¿PUEDE BEBER O TOMAR EL PECHO?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'¿VOMITA TODO?',null,111,'¿VOMITA TODO?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'¿HA TENIDO FIEBRE?',null,112,'¿HA TENIDO FIEBRE?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'¿HA TENIDO HIPOTERMIA?',null,113,'¿HA TENIDO HIPOTERMIA?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'¿HA TENIDO CONVULSIONES?',null,114,'¿HA TENIDO CONVULSIONES?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'¿HA DEJADO DE RESPIRAR?',null,115,'¿HA DEJADO DE RESPIRAR?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'¿SANGRE EN HECES?',null,116,'¿SANGRE EN HECES?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'¿MALFORMACIONES CONGENITAS?',null,117,'¿MALFORMACIONES CONGENITAS?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'LETARGICO:',null,118,'LETARGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SE VE MAL:',null,119,'SE VE MAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ALETEO(NASAL):',null,120,'ALETEO(NASAL):');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'QUEJIDO:',null,121,'QUEJIDO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'4 DIURESIS EN 24 HORAS:',null,122,'4 DIURESIS EN 24 HORAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PALIDEZ(INTENSA):',null,123,'PALIDEZ(INTENSA):');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ICTERICIA POR DEBAJO DEL OMBLIGO:',null,124,'ICTERICIA POR DEBAJO DEL OMBLIGO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PETEQUIAS:',null,125,'PETEQUIAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'EQUIMOSSIS:',null,126,'EQUIMOSSIS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'HEMORRAGIA:',null,127,'HEMORRAGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'FONTANELA(ABOMBADA):',null,128,'FONTANELA(ABOMBADA):');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SECRECION CONJUNTIVAL PURULENTA:',null,129,'SECRECION CONJUNTIVAL PURULENTA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'OMBLIGO ERITEMATOSO O CON SECRECION:',null,130,'OMBLIGO ERITEMATOSO O CON SECRECION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PUSTULAS O MUCHAS O EXTENSAS:',null,131,'PUSTULAS O MUCHAS O EXTENSAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PLACA BLANQUECINAS EN BOCA:',null,132,'PLACA BLANQUECINAS EN BOCA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SE MUEVE MENOS:',null,133,'SE MUEVE MENOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PIRAJE(SUBCOSTAL):',null,134,'PIRAJE(SUBCOSTAL):');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'STRIDOR:',null,135,'STRIDOR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RECUENTO:',null,136,'RECUENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TAQUICARDIA:',null,137,'TAQUICARDIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'FLACIDO:',null,138,'FLACIDO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CIANOSIS:',null,139,'CIANOSIS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SIBILANCIA:',null,140,'SIBILANCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RESPIRACION(RAPIDA):',null,141,'RESPIRACION(RAPIDA):');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'LLENADO CAPILAR > 2 SEGUNDOS:',null,142,'LLENADO CAPILAR > 2 SEGUNDOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'HEMORRAGIA:',null,143,'HEMORRAGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'DISTENCION (ABDOMINAL)',null,144,'DISTENCION (ABDOMINAL)');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TIENE DIARREA:',null,145,'TIENE DIARREA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'DIAGNOSTICO:',null,146,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TIENE ALGUNA DIFICULTAD PARA ALIMENTARSE:',null,147,'TIENE ALGUNA DIFICULTAD PARA ALIMENTARSE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'DIANOSTICO:',null,148,'DIANOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'HA DEJADO DE COMER:',null,149,'HA DEJADO DE COMER:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'SE ALIMENTA AL PECHO:',null,150,'SE ALIMENTA AL PECHO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RECIBE OTRA LECHE:',null,151,'RECIBE OTRA LECHE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TOCA EL SENO CON EL METON:',null,152,'TOCA EL SENO CON EL METON:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'BOCA BIEN ABIERTA:',null,153,'BOCA BIEN ABIERTA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'LABIO INFERIOR VOLTEADO HACIA AFUERA:',null,154,'LABIO INFERIOR VOLTEADO HACIA AFUERA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'AREOLA MAS VISIBLE POR ENCIMA:',null,155,'AREOLA MAS VISIBLE POR ENCIMA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'EVALUAR SUCCION:',null,156,'EVALUAR SUCCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'POSICION AL AMAMANTAR:',null,157,'POSICION AL AMAMANTAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'LA POSICION ES LA CORRECTA?',null,158,'LA POSICION ES LA CORRECTA?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'DIAGNOSTICO:',null,159,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'DIAGNOSTICO:',null,160,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'DIAGNOSTICO:',null,161,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'DIAGNOSTICO:',null,162,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'VACUNAS PENDIENTES DE LA MADRE:',null,163,'VACUNAS PENDIENTES DE LA MADRE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'VACUNAS PENDIENTES DEL MENOR:',null,164,'VACUNAS PENDIENTES DEL MENOR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'VACUNA BCG:',null,165,'VACUNA BCG:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'VACUNA HEPATITIS B:',null,166,'VACUNA HEPATITIS B:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'FECHA DE LA PROXIMA VACUNA:',null,167,'FECHA DE LA PROXIMA VACUNA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'EVALUAR OTROS PROBLEMAS Y COMPLEMENTAR EL EXA',null,168,'EVALUAR OTROS PROBLEMAS Y COMPLEMENTAR EL EXA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ESCRIBIR RECOMENDACIONES Y ORIENTACIONES DADAS:',null,169,'ESCRIBIR RECOMENDACIONES Y ORIENTACIONES DADAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CUANDO VOLVER A CONSULTA DE CONTROL:',null,170,'CUANDO VOLVER A CONSULTA DE CONTROL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'REFEREIDO A CONSULTA DE:',null,171,'REFEREIDO A CONSULTA DE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'MEDIDAD PREVENTIVAS ESPECIFICAS:',null,172,'MEDIDAD PREVENTIVAS ESPECIFICAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RECOMENDACIONES DE BUEN TRATO:',null,173,'RECOMENDACIONES DE BUEN TRATO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RECIBIO VITAMINA A EN LOS ULTIMOS 6 MESES:',null,174,'RECIBIO VITAMINA A EN LOS ULTIMOS 6 MESES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'INTERVENCION DE MEDICINA FAMILIAR:',null,175,'INTERVENCION DE MEDICINA FAMILIAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'EXAMENES DE LABORATORIO',null,176,'EXAMENES DE LABORATORIO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'ESCRIBIR LAS RECOMENDACIONES Y ORIENTACION',null,177,'ESCRIBIR LAS RECOMENDACIONES Y ORIENTACION');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CUANDO VOLVER A CONSULTA DE CONTROL?',null,178,'CUANDO VOLVER A CONSULTA DE CONTROL?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'REFERIDO A CONSULTA DE:',null,179,'REFERIDO A CONSULTA DE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'MEDIDAD PREVENTIVAS ESPECIFICAS:',null,180,'MEDIDAD PREVENTIVAS ESPECIFICAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'CEPILLADO DE DIENTES DESPUES DE CADA COMIDA:',null,181,'CEPILLADO DE DIENTES DESPUES DE CADA COMIDA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RECOMENDACIONES DE BUEN TRATO:',null,182,'RECOMENDACIONES DE BUEN TRATO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RECIBIO VITAMINA EN LOS ULTIMOS 6 MESES:',null,183,'RECIBIO VITAMINA EN LOS ULTIMOS 6 MESES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RECIBIO ALBENDAZOL EN LOS ULTIMOS 6 MESES:',null,184,'RECIBIO ALBENDAZOL EN LOS ULTIMOS 6 MESES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RECIBIO HIERRO EN LOS ULTIMOS 6 MESES:',null,185,'RECIBIO HIERRO EN LOS ULTIMOS 6 MESES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'LABORATORIO REALIZADOS:',null,186,'LABORATORIO REALIZADOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TRATAMIENTO:',null,187,'TRATAMIENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'RECOMENDACIONES SOBRE ALIMENTACION:',null,188,'RECOMENDACIONES SOBRE ALIMENTACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'EVOLUCION EN EL SERVICIO:',null,189,'EVOLUCION EN EL SERVICIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'PAUTAS PARA EL DESARROLLO DEL MENOR:',null,190,'PAUTAS PARA EL DESARROLLO DEL MENOR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'DIAGNOSTICO:',null,191,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,84,'TRATAMIENTO:',null,192,'TRATAMIENTO:');
