update hc_tipo_reg set cant_Campos=1490 where id_tipo_Reg=55
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'GENERALES:',null,1455,'GENERALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'PATOLOGICOS:',null,1456,'PATOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'TOXICOS:',null,1457,'TOXICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'FARMACOLOGICOS:',null,1458,'FARMACOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'ALERGICOS:',null,1459,'ALERGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'ODONTOLOGICOS:',null,1460,'ODONTOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'GENERALES:',null,1461,'GENERALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'GRUPO SANGUINEO:',null,1462,'GRUPO SANGUINEO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'PATOLOGICOS:',null,1463,'PATOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'TRAUMATICOS:',null,1464,'TRAUMATICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'INF. TRANSMISION SEXUAL:',null,1465,'INF. TRANSMISION SEXUAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'INMUNOLOGICOS:',null,1466,'INMUNOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'ALERGICOS:',null,1467,'ALERGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'FARMACOLOGICOS:',null,1468,'FARMACOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'OTROS ANTECEDENTES:',null,1469,'OTROS ANTECEDENTES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'OBSERVACIONES:',null,1470,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'ASPECTO GENERAL:',null,1471,'ASPECTO GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'PESO:',null,1472,'PESO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'TALLA:',null,1473,'TALLA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'IMC:',null,1474,'IMC:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'SINDROME FEBRIL:',null,1475,'SINDROME FEBRIL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'CABEZA:',null,1476,'CABEZA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'BOCA:',null,1477,'BOCA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'OBSERVACIONES:',null,1478,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,' FRECUENCIA CARDIACA:',null,1479,' FRECUENCIA CARDIACA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'ENCIAS:',null,1480,'ENCIAS:');
--EXAMEN MENTAL
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,' APARIENCIA GENERAL:',null,1481,' APARIENCIA GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'ATENCION:',null,1482,'ATENCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'MEMORIA:',null,1483,'MEMORIA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'ALTERACION DE SUEÑO:',null,1484,'ALTERACION DE SUEÑO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'APETITO:',null,1485,'APETITO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'PENSAMIENTO:',null,1486,'PENSAMIENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'SOMATIZACIONES:',null,1487,'SOMATIZACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'INTROSPECCION Y PROSPECCION:',null,1488,'INTROSPECCION Y PROSPECCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,55,'AFECTO:',null,1489,'AFECTO:');
