update hc_tipo_reg set cant_campos=262 where id_tipo_reg=59;
SELECT pg_catalog.setval('hc_campos_reg_id_campo_seq', 112063, true);
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'MOTIVO DE CONSULTA:',null,113,'MOTIVO DE CONSULTA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ENFERMEDAD ACTUAL:',null,114,'ENFERMEDAD ACTUAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'OBSESIDAD:',null,115,'OBSESIDAD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'MENTALES:',null,116,'MENTALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ENFISEMA:',null,117,'ENFISEMA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ASMA:',null,118,'ASMA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'GENERALES:',null,119,'GENERALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'PATOLOGICOS:',null,120,'PATOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'TRAUMATICOS:',null,121,'TRAUMATICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'QUIRURGICOS:',null,122,'QUIRURGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ALERGICOS:',null,123,'ALERGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'FARMACOLOGICOS:',null,124,'FARMACOLOGICOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CONSUME CIGARRILLO:',null,125,'CONSUME CIGARRILLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'FRECUENCIA CONSUMO CIGARRILLO:',null,126,'FRECUENCIA CONSUMO CIGARRILLO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CONSUME ALCOHOL:',null,127,'CONSUME ALCOHOL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'FRECUENCIA CONSUMO ALCOHOL:',null,128,'FRECUENCIA CONSUMO ALCOHOL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'DROGADICCION FRECUENCIA TIEMPO:',null,129,'DROGADICCION FRECUENCIA TIEMPO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'EXPOSICION AL HUMO TIEMPO:',null,130,'EXPOSICION AL HUMO TIEMPO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CONSUMO DE SAL:',null,131,'CONSUMO DE SAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'GRASAS:',null,132,'GRASAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ACTIVIDAD FISICA:',null,133,'ACTIVIDAD FISICA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'FRECUENCIA ACTIVIDAD FISICA:',null,134,'FRECUENCIA ACTIVIDAD FISICA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'MANEJO DEL ESTRÉS:',null,135,'MANEJO DEL ESTRÉS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'OTROS HABITOS ALIMENTARIOS:',null,136,'OTROS HABITOS ALIMENTARIOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'RIESGO DE CAIDAS:',null,137,'RIESGO DE CAIDAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'RIESGO PSICOSOCIAL:',null,138,'RIESGO PSICOSOCIAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CA SENO:',null,139,'CA SENO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CA CERVIX:',null,140,'CA CERVIX:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'GESTAS:',null,141,'GESTAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'PARTOS:',null,142,'PARTOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ABORTOS:',null,143,'ABORTOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CESAREAS:',null,144,'CESAREAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'MENOPAUSIA:',null,145,'MENOPAUSIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'FECHA ULTIMA MENSTRUACION','date2',146,'FECHA ULTIMA MENSTRUACION');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'MENARQUIAS/ESPERMARCA:',null,147,'MENARQUIAS/ESPERMARCA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'FECHA ULTIMA CITOLOGIA:','date2',148,'FECHA ULTIMA CITOLOGIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'EX MAMA/FECHA/RESULTADO',null,149,'EX MAMA/FECHA/RESULTADO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'INF TRANSMISIÓN SEXUAL:',null,150,'INF TRANSMISIÓN SEXUAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ANTECEDENTES DEL ENTORNO:',null,151,'ANTECEDENTES DEL ENTORNO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'HA SUFRIDO ALGUN TIPO DE VIOLENCIA:',null,152,'HA SUFRIDO ALGUN TIPO DE VIOLENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'USTED SE SIENTE EN RIESGO:',null,153,'USTED SE SIENTE EN RIESGO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'USTED HA GOLPEADO(A) ALGUNA VEZ POR SU PAREJA:',null,154,'USTED HA GOLPEADO(A) ALGUNA VEZ POR SU PAREJA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'USTED QUIERE HABLAR DEL TEMA Y RECIBIR ATENCION PSICOLOGICA',null,155,'USTED QUIERE HABLAR DEL TEMA Y RECIBIR ATENCION PSICOLOGICA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'TIPO DE VIOLENCIA:',null,156,'TIPO DE VIOLENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'FICHA SIVIGILA:',null,157,'FICHA SIVIGILA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ORGANOS DE LOS SENTIDOS:',null,158,'ORGANOS DE LOS SENTIDOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CARDIOVASCULAR:',null,159,'CARDIOVASCULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'RESPIRATORIO:',null,160,'RESPIRATORIO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'GASTRO - INTESTINAL:',null,161,'GASTRO - INTESTINAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'GINECOLOGICO:',null,162,'GINECOLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'UROLOGICO:',null,163,'UROLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'MUSCULO(ESQUELETICO:)',null,164,'MUSCULO(ESQUELETICO:)');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'NEUROLOGICO:',null,165,'NEUROLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'OTROS:',null,166,'OTROS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'OBSERVACIONES',null,167,'OBSERVACIONES');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'APARIENCIA GENERAL:',null,168,'APARIENCIA GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ACTITUD:',null,169,'ACTITUD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ATENCION:',null,170,'ATENCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CONCIENCIA:',null,171,'CONCIENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ORIENTACION:',null,172,'ORIENTACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'LENGUAJE:',null,173,'LENGUAJE:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'AFECTO:',null,174,'AFECTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'MEMORIA:',null,175,'MEMORIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'PENSAMIENTO:',null,176,'PENSAMIENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'HABITO:',null,177,'HABITO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SUEÑO:',null,178,'SUEÑO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ALIMENTACION:',null,179,'ALIMENTACION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'INTELIGENCIA:',null,180,'INTELIGENCIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'RETARDO MENTAL:',null,181,'RETARDO MENTAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'INTROSPECCION:',null,182,'INTROSPECCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'PROSPECCION:',null,183,'PROSPECCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SOMATIZACIONES:',null,184,'SOMATIZACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'OBSERVACIONES:',null,185,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SOSPECHA DE MALTRATO FISICO:',null,186,'SOSPECHA DE MALTRATO FISICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SOSPECHA DE VIOLENCIA SEXUAL:',null,187,'SOSPECHA DE VIOLENCIA SEXUAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SOSPECHA DE VIOLENCIA INTRAFAMILIAR:',null,188,'SOSPECHA DE VIOLENCIA INTRAFAMILIAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CONDUCTA AGRESIVA O VIOLENTA:',null,189,'CONDUCTA AGRESIVA O VIOLENTA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SINTOMATOLOGIA DEPRESIVA:',null,190,'SINTOMATOLOGIA DEPRESIVA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SINTOMATOLOGIA DE ANSIEDAD:',null,191,'SINTOMATOLOGIA DE ANSIEDAD:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'IDEAS O INTENTO DE SUICIDA:',null,192,'IDEAS O INTENTO DE SUICIDA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CONSUMO DE ALCOHOL SUSTANCIAS PSICOACTIVAS:',null,193,'CONSUMO DE ALCOHOL SUSTANCIAS PSICOACTIVAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'PENSAMIENTOS O IDEAS INCOHERENTES:',null,194,'PENSAMIENTOS O IDEAS INCOHERENTES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'VICTIMA DE DESPLAZAMIENTO:',null,195,'VICTIMA DE DESPLAZAMIENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ASPECTO GENERAL:',null,196,'ASPECTO GENERAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'OIDOS:',null,197,'OIDOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'TORAX:',null,198,'TORAX:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CARDIOVASCULAR:',null,199,'CARDIOVASCULAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'EXAMEN DE SENO:',null,200,'EXAMEN DE SENO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'PERIMETRO ABDOMINAL:',null,201,'PERIMETRO ABDOMINAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CADERA:',null,202,'CADERA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'INDICE CINTURA CADERA:',null,203,'INDICE CINTURA CADERA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'EXAMEN GENITAL EN MUJERES:',null,204,'EXAMEN GENITAL EN MUJERES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SISTEMA MUSCULOESQUELETICO:',null,205,'SISTEMA MUSCULOESQUELETICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'NEUROLOGICO:',null,206,'NEUROLOGICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ESFERA MENTAL:',null,207,'ESFERA MENTAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SINTOMATICO NERVIOSO PERIFERICO',null,208,'SINTOMATICO NERVIOSO PERIFERICO');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'COLUMNA',null,209,'COLUMNA');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'OBSERVACIONES:',null,210,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'DOLOR DERECHA:',null,211,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'DOLOR IZQUIERDA:',null,212,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SECRECION PEZON DERECHA:',null,213,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SECRECION PEZON IZQUIERDA:',null,214,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'HINCHAZON MAMA DERECHA:',null,215,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'HINCHAZON MAMA IZQUIERDA:',null,216,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'GANGLIOS DERECHA:',null,217,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'GANGLIOS IZQUIERDA:',null,218,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'MASAS DERECHA:',null,219,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'MASAS IZQUIERDA:',null,220,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'RETRACCION DERECHA:',null,221,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'RETRACCION IZQUIERDA:',null,222,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'PIEL NARANJA DERECHA:',null,223,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'PIEL NARANJA IZQUIERDA:',null,224,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'RED VENOSA DILATADA DERECHA:',null,225,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'RED VENOSA DILATADA IZQUIERDA:',null,226,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'RETRACCION PEZON DERECHA:',null,227,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'RETRACCION PEZON IZQUIERDA:',null,228,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SECRECION PEZON DERECHA:',null,229,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SECRECION PEZON IZQUIERDA:',null,230,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ADENOPATIAS AXILARES DERECHA:',null,231,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ADENOPATIAS AXILARES IZQUIERDA:',null,232,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ADENOPATIAS CLAVICULA DERECHA:',null,233,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ADENOPATIAS CLAVICULA IZQUIERDA:',null,234,'&nbsp;');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'DISURIA:',null,235,'DISURIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'POLIURIA:',null,236,'POLIURIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'NICTURIA:',null,237,'NICTURIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'GOTEO TERMINAL:',null,238,'GOTEO TERMINAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'CHORRO CALIBRE DISMINUIDO:',null,239,'CHORRO CALIBRE DISMINUIDO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'FUERZA DEL CHORRO DISMINUIDO:',null,240,'FUERZA DEL CHORRO DISMINUIDO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'TACTO RECTAL:',null,241,'TACTO RECTAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'HEMATURIA:',null,242,'HEMATURIA:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SECRECIONES:',null,243,'SECRECIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'OBSERVACIONES:',null,244,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'OTROS:',null,245,'OTROS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'OBSERVACIONES:',null,246,'OBSERVACIONES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'HDL:',null,247,'HDL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'LDL:',null,248,'LDL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'COLESTEROL TOTAL:',null,249,'COLESTEROL TOTAL:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'TRIGLICERIDOS:',null,250,'TRIGLICERIDOS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'RIESGOS POTENCIALES:',null,251,'RIESGOS POTENCIALES:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'INTERVENCION MED FLIAR:',null,252,'INTERVENCION MED FLIAR:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'DIAGNOSTICO:',null,253,'DIAGNOSTICO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'PLAN DE INTERVENCION:',null,254,'PLAN DE INTERVENCION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'REMISION:',null,255,'REMISION:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'TRATAMIENTO:',null,256,'TRATAMIENTO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'NOTAS ACLARATORIAS:',null,257,'NOTAS ACLARATORIAS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'ANAMNESIS:',null,258,'ANAMNESIS:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'SATURACION DE OXIGENO:',null,260,'SATURACION DE OXIGENO:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,59,'OBSERVACIONES:',null,261,'OBSERVACIONES:');
