update hc_campos_reg set nombre_pdf='TRATAMIENTO MEDICO' where id_tipo_Reg=55 and posicion=11;
update hc_campos_reg set nombre_pdf='INGESTION DE MEDICAMENTOS' where id_tipo_Reg=55 and posicion=12;
update hc_campos_reg set nombre_pdf='REACCIONES ALERGICAS' where id_tipo_Reg=55 and posicion=13;
update hc_campos_reg set nombre_pdf='ANESTESIA' where id_tipo_Reg=55 and posicion=14;
update hc_campos_reg set nombre_pdf='ANTIBIOTICOS' where id_tipo_Reg=55 and posicion=15;
update hc_campos_reg set nombre_pdf='HEMORRAGIAS' where id_tipo_Reg=55 and posicion=16;
update hc_campos_reg set nombre_pdf='IRRADIACIONES' where id_tipo_Reg=55 and posicion=17;
update hc_campos_reg set nombre_pdf='SINUSITIS' where id_tipo_Reg=55 and posicion=18;
update hc_campos_reg set nombre_pdf='ENF. RESPIRATORIAS' where id_tipo_Reg=55 and posicion=19;
update hc_campos_reg set nombre_pdf='CARDIOPATIAS' where id_tipo_Reg=55 and posicion=20;
update hc_campos_reg set nombre_pdf='SINTOMATICO RESPIRATORIO' where id_tipo_Reg=55 and posicion=21;
update hc_campos_reg set nombre_pdf='DIABETES' where id_tipo_Reg=55 and posicion=22;
update hc_campos_reg set nombre_pdf='FIEBRE RUEMATICA' where id_tipo_Reg=55 and posicion=23;
update hc_campos_reg set nombre_pdf='HEPATITS' where id_tipo_Reg=55 and posicion=24;
update hc_campos_reg set nombre_pdf='HIPERTENSION' where id_tipo_Reg=55 and posicion=25;
update hc_campos_reg set nombre_pdf='EMBARAZO' where id_tipo_Reg=55 and posicion=26;
update hc_campos_reg set nombre_pdf='ENF. RENALES' where id_tipo_Reg=55 and posicion=27;
update hc_campos_reg set nombre_pdf='ENF. GASTROINS.' where id_tipo_Reg=55 and posicion=28;
update hc_campos_reg set nombre_pdf='ORGANOS DE LOS SENTIDOS' where id_tipo_Reg=55 and posicion=29;
update hc_campos_reg set nombre_pdf='SIDA' where id_tipo_Reg=55 and posicion=30;
update hc_campos_reg set nombre_pdf='OTROS' where id_tipo_Reg=55 and posicion=31;