insert into hc_Tipo_reg values(92,'FURIPS','s_furips.xhtml',true,125,0);
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INF. Fecha Radicacion',null,0,'INF. Fecha Radicacion');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INF. RG',null,1,'INF. RG');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INF. No. Radicado',null,2,'INF. No. Radicado');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INF. Respuesta a glosa',null,3,'INF. Respuesta a glosa');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INF. Nro. Factura',null,4,'INF. Nro. Factura');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INF. Razon social',null,5,'INF. Razon social');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INF. Código Habilitacion ',null,6,'INF. Código Habilitacion ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INF.  nit',null,7,'INF.  nit');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Primer Apellido',null,8,'VICT. Primer Apellido');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Segundo Apellido',null,9,'VICT. Segundo Apellido');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Primer Nombre',null,10,'VICT. Primer Nombre');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Segundo Nombre',null,11,'VICT. Segundo Nombre');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Tipo Documento',null,12,'VICT. Tipo Documento');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. No. Documento',null,13,'VICT. No. Documento');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Fecha Nacimiento',null,14,'VICT. Fecha Nacimiento');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Sexo',null,15,'VICT. Sexo');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Dirección Residencia',null,16,'VICT. Dirección Residencia');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Departamento',null,17,'VICT. Departamento');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Cod',null,18,'VICT. Cod');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Cod telefono',null,19,'VICT. Cod telefono');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Municipio',null,20,'VICT. Municipio');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Cod',null,21,'VICT. Cod');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VICT. Condicion del accidentado',null,22,'VICT. Condicion del accidentado');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Accidenrte de tránsito',null,23,'EVENT. Accidenrte de tránsito');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Sismo ',null,24,'EVENT. Sismo ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Maremoto ',null,25,'EVENT. Maremoto ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Erupciones Volcánicas ',null,26,'EVENT. Erupciones Volcánicas ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Huracán',null,27,'EVENT. Huracán');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Inundaciones ',null,28,'EVENT. Inundaciones ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Avalancha ',null,29,'EVENT. Avalancha ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Deslizamiento de Tierra ',null,30,'EVENT. Deslizamiento de Tierra ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Incendio Natural',null,31,'EVENT. Incendio Natural');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Rayo ',null,32,'EVENT. Rayo ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Vendaval ',null,33,'EVENT. Vendaval ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Tornado',null,34,'EVENT. Tornado');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Explosión ',null,35,'EVENT. Explosión ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Masacre ',null,36,'EVENT. Masacre ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Mina Antipersonal ',null,37,'EVENT. Mina Antipersonal ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Combate',null,38,'EVENT. Combate');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Incendio ',null,39,'EVENT. Incendio ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Ataques a Municipios',null,40,'EVENT. Ataques a Municipios');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Otro ',null,41,'EVENT. Otro ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Cual?',null,42,'EVENT. Cual?');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Dirección de la ocurrencia',null,43,'EVENT. Dirección de la ocurrencia');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Fecha Evento/Accidente ',null,44,'EVENT. Fecha Evento/Accidente ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Hora',null,45,'EVENT. Hora');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Departamento',null,46,'EVENT. Departamento');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Cod',null,47,'EVENT. Cod');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Municipio ',null,48,'EVENT. Municipio ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Cod',null,49,'EVENT. Cod');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Zona',null,50,'EVENT. Zona');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'EVENT. Descripción del evento / accidente:',null,51,'EVENT. Descripción del evento / accidente:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VEHI. Estado Vehiculo',null,52,'VEHI. Estado Vehiculo');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VEHI. Marca ',null,53,'VEHI. Marca ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VEHI. Placa:',null,54,'VEHI. Placa:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VEHI. Tipo Servicio',null,55,'VEHI. Tipo Servicio');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VEHI. Código de la aseguradora',null,56,'VEHI. Código de la aseguradora');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VEHI. No. de la Póliza ',null,57,'VEHI. No. de la Póliza ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VEHI. Intervención de autoridad',null,58,'VEHI. Intervención de autoridad');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VEHI. Vigencia Desde ',null,59,'VEHI. Vigencia Desde ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VEHI. Vigencia Hasta',null,60,'VEHI. Vigencia Hasta');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'VEHI. Cobro Excedente Póliza',null,61,'VEHI. Cobro Excedente Póliza');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'PROP. 1er Apellido o Razón Social ',null,62,'PROP. 1er Apellido o Razón Social ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'PROP. 2do. Apellido',null,63,'PROP. 2do. Apellido');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'PROP. 1er Nombre ',null,64,'PROP. 1er Nombre ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'PROP. 2do. Nombre',null,65,'PROP. 2do. Nombre');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'PROP. Tipo de Documento ',null,66,'PROP. Tipo de Documento ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'PROP. No. Documento',null,67,'PROP. No. Documento');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'PROP. Dirección Residencia',null,68,'PROP. Dirección Residencia');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'PROP. Departamento ',null,69,'PROP. Departamento ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'PROP. Cod. ',null,70,'PROP. Cod. ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'PROP. Teléfono',null,71,'PROP. Teléfono');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'PROP. Municipio Residencia ',null,72,'PROP. Municipio Residencia ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'PROP. Cod.',null,73,'PROP. Cod.');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INVC. 1er Apellido ',null,74,'INVC. 1er Apellido ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INVC. 2do. Apellido',null,75,'INVC. 2do. Apellido');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INVC. 1er Nombre ',null,76,'INVC. 1er Nombre ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INVC. 2do. Nombre',null,77,'INVC. 2do. Nombre');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INVC. Tipo de Documento ',null,78,'INVC. Tipo de Documento ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INVC. No. Documento',null,79,'INVC. No. Documento');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INVC. Dirección Residencia',null,80,'INVC. Dirección Residencia');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INVC. Departamento ',null,81,'INVC. Departamento ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INVC. Cod. ',null,82,'INVC. Cod. ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INVC. Teléfono',null,83,'INVC. Teléfono');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INVC. Municipio Residencia',null,84,'INVC. Municipio Residencia');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'INVC. Cod.',null,85,'INVC. Cod.');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Tipo Referencia: ',null,86,'REM. Tipo Referencia: ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Fecha remisión ',null,87,'REM. Fecha remisión ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Hora Fecha remision',null,88,'REM. Hora Fecha remision');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Prestador que remite',null,89,'REM. Prestador que remite');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Código de inscripción:',null,90,'REM. Código de inscripción:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Profesional que remite: ',null,91,'REM. Profesional que remite: ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Cargo:',null,92,'REM. Cargo:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Fecha aceptación ',null,93,'REM. Fecha aceptación ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Fecha aceptacion',null,94,'REM. Fecha aceptacion');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Prestador que recibe:',null,95,'REM. Prestador que recibe:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Código de inscripción:',null,96,'REM. Código de inscripción:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Profesional que recibe: ',null,97,'REM. Profesional que recibe: ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'REM. Cargo:',null,98,'REM. Cargo:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'TRAN. Placa No.',null,99,'TRAN. Placa No.');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'TRAN. Transporto la víctima desde',null,100,'TRAN. Transporto la víctima desde');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'TRAN. Transporto la víctima Hasta',null,101,'TRAN. Transporto la víctima Hasta');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'TRAN. Tipo de Transporte',null,102,'TRAN. Tipo de Transporte');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'TRAN. Lugar donde recoge la Victima Zona',null,103,'TRAN. Lugar donde recoge la Victima Zona');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. Fecha de ingreso',null,104,'CERT. Fecha de ingreso');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. Hora Ingreso',null,105,'CERT. Hora Ingreso');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. Fecha de egreso',null,106,'CERT. Fecha de egreso');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. Hora egreso',null,107,'CERT. Hora egreso');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. Código Diagnóstico principal de Ingreso ',null,108,'CERT. Código Diagnóstico principal de Ingreso ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. Código Diagnóstico principal de Egreso',null,109,'CERT. Código Diagnóstico principal de Egreso');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. Otro código Diagnóstico principal de Ingreso ',null,110,'CERT. Otro código Diagnóstico principal de Ingreso ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. Otro código Diagnóstico principal de Egreso',null,111,'CERT. Otro código Diagnóstico principal de Egreso');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. CERT. Otro código Diagnóstico principal de Ingreso ',null,112,'CERT. CERT. Otro código Diagnóstico principal de Ingreso ');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. Otro código Diagnóstico principal de Egreso',null,113,'CERT. Otro código Diagnóstico principal de Egreso');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. 1er Apellido del Médico o Profesional tratante',null,114,'CERT. 1er Apellido del Médico o Profesional tratante');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. CERT. 2do. Apellido del Médico o Profesional tratante',null,115,'CERT. CERT. 2do. Apellido del Médico o Profesional tratante');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. 1er Nombre del Médico o Profesional tratante',null,116,'CERT. 1er Nombre del Médico o Profesional tratante');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. 2do Nombre del Médeco o Profesional tratante',null,117,'CERT. 2do Nombre del Médeco o Profesional tratante');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. CERT. Tipo Documento',null,118,'CERT. CERT. Tipo Documento');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. Número Documento',null,119,'CERT. Número Documento');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'CERT. Número de registro médico:',null,120,'CERT. Número de registro médico:');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'AMP. Gastos medicos qururgicos_1',null,121,'AMP. Gastos medicos qururgicos_1');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'AMP. Gastos medicos qururgicos_2',null,122,'AMP. Gastos medicos qururgicos_2');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'AMP. Gastos de transporte y movilización de la víctima_1',null,123,'AMP. Gastos de transporte y movilización de la víctima_1');
insert into hc_campos_reg (select nextval('hc_campos_reg_id_campo_seq')+1,92,'AMP. Gastos de transporte y movilización de la víctima_2',null,124,'AMP. Gastos de transporte y movilización de la víctima_2');
